### PR TITLE
Update the update yaml script

### PR DESCRIPTION
**Pull request by justaddcoffee**
- Move update_yaml.py script into main cli()
- Add unit tests

### CODE REVIEW

**Comment by justaddcoffee** [comment]
Making this a draft, because for some reason click can't find the update_yaml command

**Comment by justaddcoffee** [comment]
TODO:
- per convo with @caufieldjh, fix bug when updating multiple nested keys - solution for now is to support specifying nested keys like this `--keys graph_data:graph:node_path --values my/new/node/path`

**Comment by justaddcoffee** [comment]
Adding - @caufieldjh I've made a unit test [here](https://github.com/Knowledge-Graph-Hub/NEAT/blob/f0873ddee41747609fbc8db92685462163efa716/tests/test_do_update_yaml.py#L37) for this - un`skip` this once you've implemented the nested key thing above

**Comment by caufieldjh** [comment]
> TODO:
> 
> * per convo with @caufieldjh, fix bug when updating multiple nested keys - solution for now is to support specifying nested keys like this `--keys graph_data:graph:node_path --values my/new/node/path`

Done - keys now need to be specified like key1:key2:key3, but a list of different keys can still be provided, e.g. key1:key2:key3,key4:key5,key6

**Pull request merged**
