### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by justaddcoffee**
Start of a refactor to:
- move stuff into modules
- use a factory pattern for classifiers
- tidy up the use of parsed YAML
- add code to wrap holdouts

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@deepakunni3 we possibly could chat about this when you have a chance, in case you have some thoughts

**Comment by deepakunni3** [comment]
Yes, lets catch up and review this PR

**Comment by justaddcoffee** [comment]
Okay great @deepakunni3 (to be clear, this isn't much of a PR right now, just thought we should chat so I can get your thoughts on the above proposed changes)

**Comment by justaddcoffee** [comment]
@deepakunni3 ready for you to have a look - pretty major refactor

**Review by deepakunni3 — APPROVED** [review]

**Pull request merged**
