### PR TITLE
Updates for newest grape

### LINKED ISSUE #81: Update for Ensmallen / Embiggen -> grape
- [x] Where previously installing `ensmallen` and `embiggen`, install `grape`
- [x] Update imports and methods to refer to `grape`, e.g. `from grape.embedders import SkipGramEnsmallen`
- [ ] Update for `grape` native methods as per #77 

See the grape tutorials for examples: https://github.com/AnacletoLAB/grape/tree/main/tutorials

### PR DESCRIPTION
**Pull request by caufieldjh**
See linked issue (#81).

### CODE REVIEW

**Comment by caufieldjh** [comment]
Getting an ImportError:
```
 ImportError: cannot import name 'LinkPredictionTransformer' from 'grape' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/grape/__init__.py)
```
Where are the transformers now?

**Comment by caufieldjh** [comment]
Not entirely sure what to do with generating BERT embeddings for now - neat_schema doesn't include params for it, and not sure what is or isn't in Embiggen to support it

**Comment by caufieldjh** [comment]
A work in progress note:
```
  File "/home/harry/neat-env/lib/python3.8/site-packages/neat/cli.py", line 84, in run
    train_data, validation_data = model.make_train_valid_data(
  File "/home/harry/neat-env/lib/python3.8/site-packages/neat/link_prediction/model.py", line 93, in make_train_valid_data
    graph_args["directed"] = training_graph_args["directed"]
TypeError: 'str' object does not support item assignment
```
Looks like something that should be a dict isn't one - not sure what's happening yet

**Comment by caufieldjh** [comment]
This now appears to work as expected, with the sole caveat that the edge prediction methods have not been replaced with the `grape` methods - they are still our own sklearn/tf methods.

I'd like to split that part of the update into its own PR so we can complete the name change and get NEAT on Pypi.

**Review by hrshdhgd — APPROVED** [review]

**Pull request merged**
